name: Docker Image CI

on:
  push:
    branches:
      - 'main' # Only on main branch
    paths:
      - 'Dockerfile' # AND if the Dockerfile has been updated by HEAD commit

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - jdk-version: "openjdk-17-jdk-headless"
            tag: "java-17"
          - jdk-version: "openjdk-17-jdk-headless"
            tag: "java-17"
          - tag: "latest"

    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            JAVA_JDK_VERSION=${{ matrix.jdk-version }}
          tags: |
            jimetevenard/headless-coding:${{ matrix.tag }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
