name: Docker Image CI

on:
  push:
    # Only on main branch AND if either the Dockerfile or a worflow file
    # has been updated by HEAD commit
    branches:
      - 'main'
    paths:
      - 'Dockerfile' 
      - '.github/workflows/*.yml'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - jdk-version: "openjdk-17-jdk-headless"
            tag: "java-17"
          - jdk-version: "openjdk-17-jdk-headless"
            tag: "latest" # FixMe : 'duplicates' the java-17 image build with a different SHA digest
          - jdk-version: "openjdk-11-jdk-headless"
            tag: "java-11"


    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            JAVA_JDK_VERSION=${{ matrix.jdk-version }}
          tags: |
            jimetevenard/headless-coding:${{ matrix.tag }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
