name: Docker Image CI

on:
  push:
    # Only on main branch AND if either the Dockerfile or a worflow file
    # has been updated by HEAD commit
    branches:
      - 'main'
    paths:
      - 'Dockerfile' 
      - '.github/workflows/*.yml'

env:
  repository: jimetevenard/headless-coding

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - jdk_version: "openjdk-17-jdk-headless"
            image_tags_csv: "${{ env.repository }}:latest,${{ env.repository }}:java-17"
          - jdk_version: "openjdk-11-jdk-headless"
            image_tags_csv: "${{ env.repository }}:java-11"


    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            JAVA_JDK_VERSION=${{ matrix.jdk_version }}
          tags: ${{ matrix.image_tags_csv }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
